email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
phone_regex: !ruby/regexp /\A\d[0-9]{9}\z/
model:
  user:
    email_max: 255
    password_min: 6
  profile:
      name_length_max_50: 50
      length_max_255: 255
helper:
  avatar:
    size: 80
link_expired:
  hours_2: 2
per_page:
  users: 10
paginate:
  home: 6
  manage: 5

